name: Whitelist token request
description: Submit a request to add a new token to the rewards whitelist.
title: "[Whitelist Request]: <Token Name>"
labels: ["token whitelist request"]
body:
  - type: markdown
    attributes:
      value: |
        To whitelist a new token for rewards, please provide the following details:
  - type: input
    id: chain
    attributes:
      label: Chain
      description: The chain on which the token exists.
    validations:
      required: true
  - type: input
    id: address
    attributes:
      label: Token address
      description: The contract address of the token.
    validations:
      required: true
  - type: input
    id: symbol
    attributes:
      label: Token symbol
      description: The token's symbol.
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Token name
      description: The full name of the token.
    validations:
      required: true
  - type: input
    id: decimals
    attributes:
      label: Token decimals
      description: The token's decimals.
      placeholder: "18"
    validations:
      required: true
  - type: input
    id: coingecko-id
    attributes:
      label: Coingecko id
      description: The token's identifier on Coingecko.
      placeholder: "coingecko:ethereum"
    validations:
      required: true
